### ISSUE TITLE
After right clicking (landmark select) view snaps back

### ISSUE THREAD

**Issue by zarquon42b** [morphomuseum/ISE-MeshTools#14]
When selecting landmarks, each time one is selected (right clicking), the view snaps back which can be quite annoying.

**Comment by renaud-lebrun** [comment]
What do you mean by "the view snaps back" ? I do not understand.

**Comment by zarquon42b** [comment]
When you drag your mesh (middle mouse drag) to get to a better position to select/unselect a landmark (see image below), after clicking and then right click to select the view snaps back (second image)
this can be annoying if you want to gain access to multiple landmarks that require to drag the mesh first. 
Maybe there is a simple workaround or I am doing this wrong.

Drag mesh to get access (exaggerated example)
![interactive software meshtools_098](https://cloud.githubusercontent.com/assets/1515863/11687191/7095fe40-9e85-11e5-9498-a433571c0fda.png)

After clicking the view snaps back:
![interactive software meshtools_099](https://cloud.githubusercontent.com/assets/1515863/11687228/ab8b5338-9e85-11e5-8f9d-74d2d2293ef4.png)

**Comment by renaud-lebrun** [comment]
Ok, I have changed the behaviour of MeshTools inside the branch "adjustable_landmark_size".

**Comment by renaud-lebrun** [comment]
Ok, corrections have been merged to the main branch
