### ISSUE TITLE
Weird clipping with the option "keep object native coord system" is selected

### ISSUE THREAD

**Issue by zarquon42b** [morphomuseum/ISE-MeshTools#17]
When loading a mesh without centering, it (sometimes) gets clipped weirdly (here is the url of the example mesh: https://github.com/marcelluethi/statismo-shaperegistration/raw/master/data/VSD001_femur.vtk):

![selection_098](https://cloud.githubusercontent.com/assets/1515863/11745832/1f34e42a-a01b-11e5-88bb-91025b2103a7.png)

Weirdly clipped:
![selection_099](https://cloud.githubusercontent.com/assets/1515863/11745841/288a416e-a01b-11e5-82af-05f5b8ac11ca.png)

**Comment by renaud-lebrun** [comment]
Yes, that's right, it has to do with the camera "tz" and "far" values which are currently not adjusted automatically with the size of the objects. When opening a model bigger than ~30 cm long, this happens (and it should not). I will work on it.

**Comment by renaud-lebrun** [comment]
Well, I had already solved the issue, but this not the default behaviour : 
when you go in "Viewing opt. => General rendering option", click on "Adapt field of view depth", this should do the trick.

I will modify ISE-MeshTools to make this rendering option the default one (even if no .ini file has been found).

**Comment by renaud-lebrun** [comment]
But still, I am currently modifying the behaviour of the software so that the "clipping plane <<cut half>>" buttons continue to work when "keep object native coord system" is active, it was not the case

**Comment by zarquon42b** [comment]
closed by #20
