### ISSUE TITLE
Save ini file at a single user specific location

### ISSUE THREAD

**Issue by zarquon42b** [morphomuseum/ISE-MeshTools#2]
At the moment, when calling MeshTools from command line, a ini file will be saved in the directory. Would it be possible to define a fixed location, e.g. C:\Users\myuser\MeshTools.ini or /home/myuser/MeshTools.ini ?

**Comment by renaud-lebrun** [comment]
That would be a good idea... plus it would be interesting to define a "default" .ini file with default "convenient" instantiation values. For the moment, default values (for instance object colours...) are not well set.

**Comment by zarquon42b** [comment]
It would also be nice to obtain an automated size of the spheres' radii/ needle length based on the object's scale (cf. human skull vs. mouse ear)

**Comment by renaud-lebrun** [comment]
When I think about it (the .ini file enhancement), this is something quite OS specific, but probably not hard to implement. Any advice would be welcome to be able to detect on which OS ISE-MeshTools has been launched and which user is currently using it.

**Comment by zarquon42b** [comment]
I implemented a fix on Linux here: https://github.com/morphomuseum/ISE-MeshTools/tree/user-specific-ini-file
@renaud-lebrun: here is something on how to handle it on windows: http://stackoverflow.com/questions/9542611/how-to-get-the-current-users-home-directory-in-windows maybe you can try this.

**Comment by renaud-lebrun** [comment]
Ah ok, I can pull your branch at try out

**Comment by zarquon42b** [comment]
BTW: I am installing win build tools on a VM at the moment, so I can also test the windows version.

**Comment by renaud-lebrun** [comment]
Very good !

**Comment by zarquon42b** [comment]
Did you already document the setup on windows? I can compile, but the programm does not start (using VTK 6.2, Visual Studio 2013 on Win7 64bit)

**Comment by renaud-lebrun** [comment]
My wife is currently giving birth, so I won't be available soon :).

I did not write anything yet but your can try out the windows binaries available on morphomuseum to see if It comes from the virtual emulator.
Best regards,
Renaud

**Comment by zarquon42b** [comment]
Oh, 
good luck with that. 
I only had linked the exe against the wrong glew.dll.

Best
Stefan
