### ISSUE TITLE
Add option to export all data in original space.

### ISSUE THREAD

**Issue by zarquon42b** [morphomuseum/ISE-MeshTools#3]
It would be cool to have an option to export all data (landmarks, curves, etc) in the same coordinate system as the original data (similar to the option when you save a surface). I do not know if you store the transforms, if yes, one could simply apply the inverse of the combined transforms.

**Comment by renaud-lebrun** [comment]
Yes that's right, but then how should ISE-MeshTools behave when landmarks are set on a "composite" specimen composed of more than 1 surface having different position matrices (for instance : landmarks set on 1 cranium and 1 mandible) ?

=> Maybe ISE-MeshTools could detect whether more than one surfaces are loaded and only activate this option in the case of a unique opened surface file.

**Comment by zarquon42b** [comment]
Maybe, instead an option to might be sensible to import data (as is) and center the camera to the bounding box of all the objects in the scene. I am thinking of two already aligned meshes that are far away from the origin. The simple export would take care that all data is still in the same coordinate system. (important if you want to let the semi-landmarks slide on the surface)

**Comment by renaud-lebrun** [comment]
Yes, this would be a good solution.
=> But I would think of this new camera behaviour as optional. I would prefer that it does not override the current fixed camera behaviour (I use it for teaching purposes, to orient many specimens and to produce centred nexus files).
