### ISSUE TITLE
Instructions to compile on windows... and Mac

### ISSUE THREAD

**Issue by renaud-lebrun** [morphomuseum/ISE-MeshTools#7]
I have to write a "howto" compile ISE-MeshTools on a Xindows machine.

We have to find a collaborator who could try to compile ISE-MeshTools on Mac. Any idea ?

**Comment by zarquon42b** [comment]
I will do the Linux part. Unfortunately, on my new machine the Mac VM does not work anymore and I don't know any mac developers.

**Comment by renaud-lebrun** [comment]
We have Mac developers at the ISEM (but more on the molecular side of biology), I will try out.

**Comment by zarquon42b** [comment]
I managed to install osx yosemite on a vm and will try to checkout if I can get it compiled.

**Comment by renaud-lebrun** [comment]
Sorry I did not inform you but Jean Dumoncel informed me last week that he managed to compile Meshtools on OS X and would learn soon to use Git and Github to add a branch and write the little modifications needed...
All the best,
Renaud
